### ISSUE TITLE
3.14.0 Build 938 NPE

### ISSUE THREAD

**Issue by raum266** [NoCheatPlus/Issues#112]
Popping up nearly every time entities are attacked. Seems to effect everyone - It is not quite 100% of the attacks, but very close.

No real changes to the NCP config, outside of adjusting flight times due to the massive spam being generated in 1.9 from that.

Occurring with the msot recent Spigot as of this morning, bc01c3a-935349e

[Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to NoCheatPlus v3.14.0-SNAPSHOT-sMD5NET-b938
org.bukkit.event.EventException
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:88) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:557) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:589) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1206) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:814) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.EntityHuman.attack(EntityHuman.java:999) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.EntityPlayer.attack(EntityPlayer.java:1141) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1541) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
  at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NullPointerException

**Comment by minoneer** [comment]
Getting the exact same exception when someone attacks entities, also build 938, spigot 1.9

**Comment by asofold** [comment]
Thanks a lot - should be fixed in build 939.

**Comment by minoneer** [comment]
Great, thx
