### ISSUE TITLE
Error Spam 

### ISSUE THREAD

**Issue by tara81** [NoCheatPlus/Issues#132]
http://pastebin.com/Rv8wMdRp
Update ::: Found entire error http://pastebin.com/KAYR8GFq

Caused by: java.lang.ClassCastException: org.zonedabone.commandsigns.proxy.PlayerProxy cannot be cast to org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer

Looks like no cheat doesn't like the  commandsigns plugin , it teleports a player to an area by selecting the sign in my minigame .

http://dev.bukkit.org/bukkit-plugins/command-signs/

**Comment by asofold** [comment]
Could you past the full error log? It seems to be cut off...

**Comment by tara81** [comment]
That is all it says 

[15:39:36] [Server thread/ERROR]: Could not pass event EntityDamageEvent to NoCheatPlus v3.14.0-SNAPSHOT-sMD5NET-b942
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.jar:git-Paper-506]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.jar:git-Paper-506]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-506]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-506]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-506]
	at mc.alk.arena.util.compat.v1_7_R3.PlayerHelper.setHealth(PlayerHelper.java:31) [BattleArena.jar:?]
	at mc.alk.arena.util.PlayerUtil.setHealth(PlayerUtil.java:79) [BattleArena.jar:?]
	at mc.alk.arena.util.PlayerUtil.setHealth(PlayerUtil.java:75) [BattleArena.jar:?]
	at mc.alk.arena.competition.TransitionController.transition(TransitionController.java:175) [BattleArena.jar:?]
	at mc.alk.arena.competition.TransitionController.transition(TransitionController.java:109) [BattleArena.jar:?]
	at mc.alk.arena.competition.TransitionController.transition(TransitionController.java:240) [BattleArena.jar:?]
	at mc.alk.arena.competition.TransitionController.transition(TransitionController.java:109) [BattleArena.jar:?]
	at mc.alk.arena.competition.Competition.performTransition(Competition.java:136) [BattleArena.jar:?]
	at mc.alk.arena.competition.match.Match.doTransition(Match.java:904) [BattleArena.jar:?]
	at mc.alk.arena.competition.match.Match.access$1300(Match.java:105) [BattleArena.jar:?]
	at mc.alk.arena.competition.match.Match$5.run(Match.java:926) [BattleArena.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.9.jar:git-Paper-506]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.jar:git-Paper-506]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:784) [patched_1.9.jar:git-Paper-506]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-506]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-506]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-506]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException
[15:39:36] [Server thread/WARN]: Unexpected NavigationListener add
[15:39:36] [Server thread/WARN]: Unexpected NavigationListener add

It is from console.

**Comment by tara81** [comment]
Finally got the entire error !
http://pastebin.com/KAYR8GFq

**Comment by asofold** [comment]
Thanks a lot. The problem seems to be, that NCP currently isn't compatible with proxy players used by other plugins, concerning at least damage events.

**Comment by asofold** [comment]
Currently out of scope, thus postponed. Open to contribution, if it's doable in a simple and somewhat consistent way...

https://github.com/NoCheatPlus/Issues/projects/6
