### ISSUE TITLE
IndexOutOfBoundsException on fastclick check

### ISSUE THREAD

**Issue by RoboMWM** [NoCheatPlus/Issues#149]
https://gist.github.com/RoboMWM/bcc4b73ccbee3a7199ae40772c283dee

```
2016-04-02 23:44:47 [INFO] piggywiggy1999 has just earned the achievement [Benchmarking]
2016-04-02 23:44:49 [INFO] [NoCheatPlus] piggywiggy1999 failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:50 [INFO] [NoCheatPlus] missxgamer failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:50 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:55 [INFO] [NoCheatPlus] thenameislexie failed FastClick: tried to move items in their inventory too quickly. VL 91.
2016-04-02 23:44:56 [FATAL] Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-628]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_72]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1921) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-628]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-628]
	... 5 more
2016-04-02 23:44:59 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 149383.
2016-04-02 23:45:00 [INFO] [NoCheatPlus] missxgamer failed FastClick: tried to move items in their inventory too quickly. VL 74692.
2016-04-02 23:45:05 [FATAL] Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-628]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_72]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1921) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-628]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-628]
	... 5 more
```

```
2016-04-02 23:55:38 [INFO] [NoCheatPlus] thenameislexie failed FastClick: tried to move items in their inventory too quickly. VL 149392.
2016-04-02 23:55:48 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 373465.
2016-04-02 23:56:15 [INFO] piggywiggy1999 issued server command: /help
2016-04-02 23:56:22 [INFO] thenameislexie issued server command: /unclaim
2016-04-02 23:56:35 [INFO] [NoCheatPlus] Music_girl_13 failed FastClick: tried to move items in their inventory too quickly. VL 448147.
2016-04-02 23:56:37 [FATAL] Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-628]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_72]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1921) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-628]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-628]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-628]
	... 5 more
```

```
2016-04-03 00:01:47 [INFO] ---- Version information ----[m
2016-04-03 00:01:47 [INFO] #### Server ####[m
2016-04-03 00:01:47 [INFO] git-Paper-628 ~MC: 1.9.2~[m
2016-04-03 00:01:47 [INFO]   detected: 1.9.2[m
2016-04-03 00:01:47 [INFO] #### NoCheatPlus ####[m
2016-04-03 00:01:47 [INFO] Plugin: 3.14.0-SNAPSHOT-sMD5NET-b958[m
2016-04-03 00:01:47 [INFO] MCAccess: 1.9 / Spigot-CB-1.9_R1[m
2016-04-03 00:01:47 [INFO] Features:[m
2016-04-03 00:01:47 [INFO]   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9[m
2016-04-03 00:01:47 [INFO]   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency[m
2016-04-03 00:01:47 [INFO]   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter[m
2016-04-03 00:01:47 [INFO] Hooks: AllViolations~NCP~ 1.0[m
2016-04-03 00:01:47 [INFO] #### Related Plugins ####[m
2016-04-03 00:01:47 [INFO] ProtocolLib v3.7.0-SNAPSHOT-b258[m
```

**Comment by RoboMWM** [comment]
As for the check itself, I found that it's actually being caused by a plugin. https://github.com/BenWoodworth/FastCraftPlus/issues/18

**Comment by RoboMWM** [comment]
Hmm, seems like this might not be an NCP bug, but a fastcraft one, based on other reports I've been seeing.

**Comment by RoboMWM** [comment]
Actually I'm not sure what plugin it is :s

https://aquifermc.org/threads/server-crash-what-happen.114/#post-933 does not use Fastcraft+, will verify if https://www.spigotmc.org/threads/fastcraft.133803/page-5#post-1453130 is indeed not running NCP

**Comment by asofold** [comment]
Could suspect some plugin accessing something asynchronously, but i don't have a clue.

**Comment by MyPictures** [comment]
@asofold do you not think that a VL 149383 is insanely high? Could a too high VL throw a OutOfBounds execution exception? Can a insanely high VL cause issues at all? Remember that time you changed fastbreak to throw a less higher VL? Was that just cosmetic or did it have a real reason?

**Comment by asofold** [comment]
@MyPictures There could be an overflow with extreme levels. 100000 +- is not extreme in terms of integer arithmetics. If it makes sense to have that, is another question.

**Comment by RoboMWM** [comment]
So at least for my issue, it seems to be a FastCraft+ thing. https://github.com/BenWoodworth/FastCraftPlus/issues/20

Unsure about others with reports, but seems to be an elusive bug regarding finding the plugin at fault.
