### ISSUE TITLE
disconnect.spam and java.io.IOException: Stream Closed issues...

### ISSUE THREAD

**Issue by L4BORG** [NoCheatPlus/Issues#189]
So I've been noticing some issues lately (last few NCP builds, possibly more), currently we're running:

```
>ver
[03:05:14 INFO]: This server is running CraftBukkit version git-TacoSpigot-"a4a61e1" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[03:05:14 INFO]: Checking version, please wait...
```

```
>ncp version
[03:05:42 INFO]: ---- Version information ----
[03:05:42 INFO]: #### Server ####
[03:05:42 INFO]: git-TacoSpigot-"a4a61e1" ~MC: 1.8.8~
[03:05:42 INFO]:   detected: 1.8.8
[03:05:42 INFO]: #### NoCheatPlus ####
[03:05:42 INFO]: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b988
[03:05:42 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[03:05:42 INFO]: Features:
[03:05:42 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[03:05:42 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[03:05:42 INFO]:   defaults: pvpKnockBackVelocity
[03:05:42 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[03:05:42 INFO]: Hooks: AllViolations~NCP~ 1.0
[03:05:42 INFO]: #### Related Plugins ####
[03:05:42 INFO]: ProtocolLib v3.6.5
```

Now the problem is I've been seeing more and more such things in console:

```
[02:37:27] [Server thread/INFO]: Player12 lost connection: disconnect.spam
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
[02:37:27] [Server thread/WARN]: handleDisconnection() called twice
```

followed by:

```
[02:37:48] [File IO Thread/WARN]: java.io.IOException: Stream Closed
[02:37:48] [File IO Thread/WARN]:   at java.io.RandomAccessFile.seek0(Native Method)
[02:37:48] [File IO Thread/WARN]:   at java.io.RandomAccessFile.seek(RandomAccessFile.java:557)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.RegionFile.a(RegionFile.java:255)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.RegionFile.a(RegionFile.java:192)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.RegionFile$ChunkBuffer.close(RegionFile.java:304)
[02:37:48] [File IO Thread/WARN]:   at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241)
[02:37:48] [File IO Thread/WARN]:   at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
[02:37:48] [File IO Thread/WARN]:   at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.ChunkRegionLoader.b(ChunkRegionLoader.java:181)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.ChunkRegionLoader.c(ChunkRegionLoader.java:162)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.FileIOThread.c(FileIOThread.java:35)
[02:37:48] [File IO Thread/WARN]:   at net.minecraft.server.v1_8_R3.FileIOThread.run(FileIOThread.java:28)
[02:37:48] [File IO Thread/WARN]:   at java.lang.Thread.run(Thread.java:745)
```

and I'm not sure what exactly is causing this... we're also running latest https://github.com/MylesIsCool/ViaVersion/ but I don't think it has anything to do with this...

Any ideas?

Aside from that we're having some issues with memory leaks but I don't think NCP is the one to blame...

**Comment by asofold** [comment]
The 'handleDisconnection() called twice' message looks like an extreme case, though it's been happening more often since 1.8/1.9 anyway.

Since disconnect.spam appears to be the kick reason (the vanilla spam check), it just be packets that had still been queued for processing, supposedly more text/command messages by that player.

While NCP may adapt to a specific version of Minecraft, it won't activate 1.9-specific workarounds if it detects the server to be 1.8.x. That shouldn't be the issue here, though.
Concerning the protocol builds i am not sure - there could be many things happening...
The packets still getting processed could be related to any of ProtocolLib, 1.8.x, TacoSpigot, ViaVersion, however the server seems to detect the player already being disconnected, so there probably is no real issue with that.

Concerning memory leaks, currently no idea. NCP could store more data per player, but it should always be limited (even if it is a lot).

So right now, i don't have a better idea than that the multiple messages may be 'ok-ish' in case of the player having sent many text/command messages, but can't tell much about if/why it's specific to that very setup of (Taco+ProtocolLib+Via). Perhaps someone else could tell...
