### ISSUE TITLE
could not pass fake block break event

### ISSUE THREAD

**Issue by AssasinSheep** [NoCheatPlus/Issues#290]
[21:52:55 ERROR]: Could not pass event FakeBlockBreakEvent to CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-570526c-c1b529e]
        at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:104) [mcMMO.jar:?]
        at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.dropBlocks(WoodcuttingManager.java:120) [mcMMO.jar:?]
        at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.processTreeFeller(WoodcuttingManager.java:104) [mcMMO.jar:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:218) [mcMMO.jar:?]
        at sun.reflect.GeneratedMethodAccessor219.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:293) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:219) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:848) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-570526c-c1b529e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-570526c-c1b529e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/utilities/BlockProperties
        at me.asofold.bpl.cncp.hooks.mcmmo.HookFacadeImpl.getToolProps(HookFacadeImpl.java:137) ~[?:?]
        at me.asofold.bpl.cncp.hooks.mcmmo.HookFacadeImpl.blockBreakLowest(HookFacadeImpl.java:171) ~[?:?]
        at me.asofold.bpl.cncp.hooks.mcmmo.HookmcMMO.onBlockBreakLowest(HookmcMMO.java:142) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-570526c-c1b529e]

**Comment by Janmm14** [comment]
https://github.com/NoCheatPlus/Issues/blob/master/CONTRIBUTING.md
5.

**Comment by asofold** [comment]
Please check cncp builds at: http://ci.md-5.net/job/CompatNoCheatPlus/

Build 86 might fix that issue.

On the medium run, cncp will be discontinued, but i'll attempt to build something right into NCP, at least for most that cncp did so far.

**Comment by asofold** [comment]
Use latest NCP + cncp.
