### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus

### ISSUE THREAD

**Issue by ItsHarry** [NoCheatPlus/Issues#298]
NCP version: b1022
Spigot: git-Spigot-5073b0f-07c3001 ~MC: 1.8.8

Also running ViaVersion

```java
[16:37:14] [Netty Epoll Server IO #1/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.NullPointerException
	at fr.neatmonster.nocheatplus.checks.net.NetConfigCache.getConfig(NetConfigCache.java:41) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.CatchAllAdapter.onPacketReceiving(CatchAllAdapter.java:55) ~[NoCheatPlus.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:3.6.5]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:3.6.5]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639) [ProtocolLib.jar:3.6.5]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606) [ProtocolLib.jar:3.6.5]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:332) [ProtocolLib.jar:3.6.5]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:297) [ProtocolLib.jar:3.6.5]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:546) [ProtocolLib.jar:3.6.5]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278) [ProtocolLib.jar:3.6.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[16:37:14] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInBlockDig@486094a[
    a=BlockPosition{x=10, y=72, z=-1}
    b=up
    c=START_DESTROY_BLOCK
  ]
```

**Comment by L4BORG** [comment]
We're having exact the same issue:

```
[03:46:42 ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.NullPointerException
        at fr.neatmonster.nocheatplus.checks.net.NetConfigCache.getConfig(NetConfigCache.java:41) ~[NoCheatPlus.jar:?]
        at fr.neatmonster.nocheatplus.checks.net.protocollib.CatchAllAdapter.onPacketReceiving(CatchAllAdapter.java:55) ~[NoCheatPlus.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-TacoSpigot-"65fd35f"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched.jar:git-TacoSpigot-"65fd35f"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[03:46:42 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayInBlockDig@7b456fff[
    a=BlockPosition{x=6, y=63, z=3}
    b=north
    c=START_DESTROY_BLOCK
  ]
```

```
>ncp ver
[03:48:10 INFO]: ---- Version information ----
[03:48:10 INFO]: #### Server ####
[03:48:10 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[03:48:10 INFO]:   detected: 1.8.8
[03:48:10 INFO]: #### NoCheatPlus ####
[03:48:10 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1027
[03:48:10 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[03:48:10 INFO]: Features:
[03:48:10 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[03:48:10 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[03:48:10 INFO]:   defaults: pvpKnockBackVelocity
[03:48:10 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[03:48:10 INFO]: #### Related Plugins ####
[03:48:10 INFO]: ProtocolLib v4.1.0
```

Latest BungeeCord, latest ViaVersion.

**Comment by asofold** [comment]
Looks like a player with "no world".

Build 1028 contains an attempt to work around this, can't guarantee that it'll mend all cases, as i can't reproduce it.

Is anything else known about when this happens?
* Have players changed the world or logged in/out very close to the point of time of the exceoption?
* Does this happen often or is it rather a rare event?

**Comment by ItsHarry** [comment]
If player.getWorld() returned null, it wouldn't throw NPE would it?

Isn't it the player object on NetConfigCache.java:41 that is null?

**Comment by asofold** [comment]
OOPS -  an NPE would result at world.getName, but not in that class at that line, so that's right.

What do we do with null players...

does this happen often?

**Comment by ItsHarry** [comment]
It's a rare error. When it happens, there's like 20 of the same error (but with different packet types) in a row in the logs.

It may possibly be linked to players being kicked for sending too many packets? It seems one guy got kicked by NCP for sending too many packets just before the error spam occurred. Or the kick could be a result of this error, idk

**Comment by asofold** [comment]
Seems likely that the player may have been kicked just before.

**Comment by asofold** [comment]
Assume fixed.
