### ISSUE TITLE
System out put!

### ISSUE THREAD

**Issue by MikuSnow** [NoCheatPlus/Issues#300]
[12:12:39] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to NoCheatPlus v3.13.7-RC-sMD5NET-b925
org.bukkit.event.EventException

        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/actions/Action
        at fr.neatmonster.nocheatplus.config.ConfigManager$1.newActionFactory(ConfigManager.java:29) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigManager.getActionFactory(ConfigManager.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFile.setActionFactory(ConfigFile.java:15) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getDefaultActionList(ConfigFileWithActions.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getOptimizedActionList(ConfigFileWithActions.java:47) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.chat.ChatConfig.<init>(ChatConfig.java:163) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.chat.ChatConfig.getConfig(ChatConfig.java:61) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.chat.ChatListener.onPlayerLogin(ChatListener.java:237) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: fr.neatmonster.nocheatplus.actions.Action
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
        at fr.neatmonster.nocheatplus.config.ConfigManager$1.newActionFactory(ConfigManager.java:29) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigManager.getActionFactory(ConfigManager.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFile.setActionFactory(ConfigFile.java:15) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getDefaultActionList(ConfigFileWithActions.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getOptimizedActionList(ConfigFileWithActions.java:47) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.chat.ChatConfig.<init>(ChatConfig.java:163) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.chat.ChatConfig.getConfig(ChatConfig.java:61) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.chat.ChatListener.onPlayerLogin(ChatListener.java:237) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 13 more
[12:12:39] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to NoCheatPlus v3.13.7-RC-sMD5NET-b925
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/hooks/NCPExemptionManager
        at fr.neatmonster.nocheatplus.NoCheatPlus$7.onPlayerJoinLowest(NoCheatPlus.java:1198) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: fr.neatmonster.nocheatplus.hooks.NCPExemptionManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
        at fr.neatmonster.nocheatplus.NoCheatPlus$7.onPlayerJoinLowest(NoCheatPlus.java:1198) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 14 more
[12:12:39] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to NoCheatPlus v3.13.7-RC-sMD5NET-b925
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/actions/Action
        at fr.neatmonster.nocheatplus.config.ConfigManager$1.newActionFactory(ConfigManager.java:29) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigManager.getActionFactory(ConfigManager.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFile.setActionFactory(ConfigFile.java:15) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getDefaultActionList(ConfigFileWithActions.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getOptimizedActionList(ConfigFileWithActions.java:47) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.combined.CombinedConfig.<init>(CombinedConfig.java:90) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.combined.CombinedConfig.getConfig(CombinedConfig.java:46) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.combined.CombinedData.getData(CombinedData.java:40) ~[?:?]
        at fr.neatmonster.nocheatplus.players.DataManager.onPlayerJoin(DataManager.java:179) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: fr.neatmonster.nocheatplus.actions.Action
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
        at fr.neatmonster.nocheatplus.config.ConfigManager$1.newActionFactory(ConfigManager.java:29) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigManager.getActionFactory(ConfigManager.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFile.setActionFactory(ConfigFile.java:15) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getDefaultActionList(ConfigFileWithActions.java:63) ~[?:?]
        at fr.neatmonster.nocheatplus.config.ConfigFileWithActions.getOptimizedActionList(ConfigFileWithActions.java:47) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.combined.CombinedConfig.<init>(CombinedConfig.java:90) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.combined.CombinedConfig.getConfig(CombinedConfig.java:46) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.combined.CombinedData.getData(CombinedData.java:40) ~[?:?]
        at fr.neatmonster.nocheatplus.players.DataManager.onPlayerJoin(DataManager.java:179) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 14 more

System out put these!
A few time can make latest.log be very large.

**Comment by asofold** [comment]
That build of NCP is quite old. Currently Jenkins carries the latest builds: http://ci.md-5.net/job/NoCheatPlus/

Build 1029 currently might be ok to use.

**Comment by asofold** [comment]
Looking at it again, i see the following:
* Outdated build of NCP.
* Likely there is a duplicate build of NCP, incompatible version of CompatNoCheatPlus (cncp).

So my suggestion is to check for duplicate jar files (possibly renamed or saved under a different name or moved to a folder that still gets checked for plugins) - and to switch to NCP build 1030 or later (Jenkins) and in this case also use the latest build of CompatNoCheatPlus if you are using that at all.
