### ISSUE TITLE
Build 1033: /ncp reload causes RuntimeException (Already disabled)

### ISSUE THREAD

**Issue by RoboMWM** [NoCheatPlus/Issues#313]
```
2016-11-23 11:41:24 [Server thread/INFO] [NoCheatPlus] §cNCP: §fReloading configuration...
2016-11-23 11:41:24 [Server thread/INFO] [NoCheatPlus] McAccess set to: 1.4.5-1.11|? / CB-Reflect
2016-11-23 11:41:24 [Server thread/WARN] Unexpected exception while parsing console command "ncp reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'ncp' in plugin NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1033
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.11.jar:git-Paper-932]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.jar:git-Paper-932]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[patched_1.11.jar:git-Paper-932]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:637) [patched_1.11.jar:git-Paper-932]
	at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:441) [patched_1.11.jar:git-Paper-932]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.11.jar:git-Paper-932]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-932]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-932]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.RuntimeException: Already disabled.
	at fr.neatmonster.nocheatplus.components.registry.event.GenericInstanceHandle$ReferenceCountHandle.getNewHandle(GenericInstanceHandle.java:106) ~[?:?]
	at fr.neatmonster.nocheatplus.components.registry.DefaultGenericInstanceRegistry$Registration.getHandle(DefaultGenericInstanceRegistry.java:127) ~[?:?]
	at fr.neatmonster.nocheatplus.components.registry.DefaultGenericInstanceRegistry.getGenericInstanceHandle(DefaultGenericInstanceRegistry.java:244) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.getGenericInstanceHandle(NoCheatPlus.java:1492) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.blocks.BlockChangeTracker.updateBlockCacheHandle(BlockChangeTracker.java:651) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.updateBlockChangeTracker(NoCheatPlus.java:1197) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus.processReload(NoCheatPlus.java:1163) ~[?:?]
	at fr.neatmonster.nocheatplus.NoCheatPlus$1ReloadHook.onReload(NoCheatPlus.java:965) ~[?:?]
	at fr.neatmonster.nocheatplus.command.admin.ReloadCommand.handleReloadCommand(ReloadCommand.java:94) ~[?:?]
	at fr.neatmonster.nocheatplus.command.admin.ReloadCommand.onCommand(ReloadCommand.java:52) ~[?:?]
	at fr.neatmonster.nocheatplus.command.NoCheatPlusCommand.onCommand(NoCheatPlusCommand.java:162) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.11.jar:git-Paper-932]
	... 8 more
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added block-info for Minecraft 1.5 blocks.
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added block-info for Minecraft 1.6.1 blocks.
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added block-info for Minecraft 1.7.2 blocks.
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added block-info for Minecraft 1.8 blocks.
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added block-info for Minecraft 1.9 blocks.
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added block-info for Minecraft 1.10 blocks.
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Removed hook: AllViolations(NCP) [1.0].
2016-11-23 11:41:24 [Craft Scheduler Thread - 2/INFO] [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
2016-11-23 11:41:24 [Server thread/WARN] [NoCheatPlus] The block breaking data is incomplete, default to allow instant breaking:
--- Missing entries -------------------------------
* MISSING 218(OBSERVER / SOLID+GROUND) 
* MISSING 219(WHITE_SHULKER_BOX / SOLID+GROUND) 
* MISSING 220(ORANGE_SHULKER_BOX / SOLID+GROUND) 
* MISSING 221(MAGENTA_SHULKER_BOX / SOLID+GROUND) 
* MISSING 222(LIGHT_BLUE_SHULKER_BOX / SOLID+GROUND) 
* MISSING 223(YELLOW_SHULKER_BOX / SOLID+GROUND) 
* MISSING 224(LIME_SHULKER_BOX / SOLID+GROUND) 
* MISSING 225(PINK_SHULKER_BOX / SOLID+GROUND) 
* MISSING 226(GRAY_SHULKER_BOX / SOLID+GROUND) 
* MISSING 227(SILVER_SHULKER_BOX / SOLID+GROUND) 
* MISSING 228(CYAN_SHULKER_BOX / SOLID+GROUND) 
* MISSING 229(PURPLE_SHULKER_BOX / SOLID+GROUND) 
* MISSING 230(BLUE_SHULKER_BOX / SOLID+GROUND) 
* MISSING 231(BROWN_SHULKER_BOX / SOLID+GROUND) 
* MISSING 232(GREEN_SHULKER_BOX / SOLID+GROUND) 
* MISSING 233(RED_SHULKER_BOX / SOLID+GROUND) 
* MISSING 234(BLACK_SHULKER_BOX / SOLID+GROUND)

**Comment by asofold** [comment]
Thank you very much! Should be fixed in build 1035.
