### ISSUE TITLE
Could not pass event PlayerMoveEvent to NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1042

### ISSUE THREAD

**Issue by L4BORG** [NoCheatPlus/Issues#328]
#### Short description of the issue.
```
[16:38:20 ERROR]: Could not pass event PlayerMoveEvent to NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1042
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at fr.neatmonster.nocheatplus.compat.blocks.changetracker.OnGroundReference.advanceDualEntries(OnGroundReference.java:287) ~[?:?]
        at fr.neatmonster.nocheatplus.compat.blocks.changetracker.OnGroundReference.advance(OnGroundReference.java:274) ~[?:?]
        at fr.neatmonster.nocheatplus.compat.blocks.changetracker.BlockChangeTracker.isOnGround(BlockChangeTracker.java:707) ~[?:?]
        at fr.neatmonster.nocheatplus.utilities.location.RichBoundsLocation.isOnGroundOpportune(RichBoundsLocation.java:918) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.moving.magic.LostGround.lostGroundPastState(LostGround.java:101) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.moving.magic.LostGround.lostGround(LostGround.java:89) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.moving.player.CreativeFly.check(CreativeFly.java:107) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.moving.MovingListener.checkPlayerMove(MovingListener.java:806) ~[?:?]
        at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove(MovingListener.java:477) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        ... 16 more
```

#### Complete output of the _ncp version_ command (please prefer text here).
```
>ncp version
[16:38:57 INFO]: ---- Version information ----
[16:38:57 INFO]: #### Server ####
[16:38:57 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[16:38:57 INFO]:   detected: 1.8.8
[16:38:57 INFO]: #### NoCheatPlus ####
[16:38:57 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1042
[16:38:57 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[16:38:57 INFO]: Features:
[16:38:57 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[16:38:57 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[16:38:57 INFO]:   defaults: pvpKnockBackVelocity
[16:38:57 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[16:38:57 INFO]: #### Related Plugins ####
[16:38:57 INFO]: ProtocolLib v3.6.5
```

#### How to reproduce the issue (is it random / always happens / side conditions)?
I think it's random and I think so far we only saw it on creative server.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Latest BungeeCord, latest ViaVersion ([16:40:48 INFO]: ViaVersion 1.0.2-SNAPSHOT)

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
N/A

**Comment by asofold** [comment]
Thank you!

Build 1043 addresses this issue. The iteration shouldn't lead to an endless loop, i just keep it 'bleeding' due to the nature of recent changes.
