### ISSUE TITLE
Error on server 1.8.8

### ISSUE THREAD

**Issue by Skilzar** [NoCheatPlus/Issues#335]
#### Short description of the issue.
[12:28:22] [Thread-2044/INFO]: UUID of player lroneaqle is e95a7924-9c08-315a-9a50-41838be89456
[12:28:22] [Thread-2045/INFO]: UUID of player lroneaqle is e95a7924-9c08-315a-9a50-41838be89456
[12:28:22] [Thread-2046/INFO]: UUID of player lroneaqle is e95a7924-9c08-315a-9a50-41838be89456
[12:28:22] [Netty Epoll Server IO #1/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:143) ~[ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$4e9b044e.getWorld(<generated>) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.NetStatic.getWorldConfig(NetStatic.java:179) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.CatchAllAdapter.onPacketReceiving(CatchAllAdapter.java:75) ~[NoCheatPlus.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
[12:28:22] [Server thread/INFO]: [mcjobs] Unable to load lroneaqle.dat...  Creating file!
[12:28:22] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload@6705a6c7[
    a=REGISTER
    b=UnpooledHeapByteBuf(ridx: 0, widx: 27, cap: 27)
  ]

[12:28:22] [Server thread/INFO]: lroneaqle[/185.57.30.92:15537] logged in with entity id 335344 at ([world]65.41212786387126, 70.0, -8.585608745828333)
[12:28:22] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@6ecd4945[id=e95a7924-9c08-315a-9a50-41838be89456,name=lroneaqle,properties={textures=[com.mojang.authlib.properties.Property@7febebeb]},legacy=false] (/185.57.30.92:15538): §cТакой игрок уже играет на сервере
[12:28:22] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@6fb7ff56[id=e95a7924-9c08-315a-9a50-41838be89456,name=lroneaqle,properties={textures=[com.mojang.authlib.properties.Property@57452556]},legacy=false] (/185.57.30.92:15539): §cТакой игрок уже играет на сервере
[12:28:22] [Server thread/INFO]: com.mojang.authlib.GameProfile@6ecd4945[id=e95a7924-9c08-315a-9a50-41838be89456,name=lroneaqle,properties={textures=[com.mojang.authlib.properties.Property@7febebeb]},legacy=false] (/185.57.30.92:15538) lost connection: §cТакой игрок уже играет на сервере
[12:28:22] [Server thread/INFO]: com.mojang.authlib.GameProfile@6fb7ff56[id=e95a7924-9c08-315a-9a50-41838be89456,name=lroneaqle,properties={textures=[com.mojang.authlib.properties.Property@57452556]},legacy=false] (/185.57.30.92:15539) lost connection: §cТакой игрок уже играет на сервере
[12:28:22] [Thread-2047/INFO]: UUID of player lroneaqle is e95a7924-9c08-315a-9a50-41838be89456
[12:28:22] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@27add873[id=e95a7924-9c08-315a-9a50-41838be89456,name=lroneaqle,properties={textures=[com.mojang.authlib.properties.Property@41fa89ae]},legacy=false] (/185.57.30.92:15540): §cТакой игрок уже играет на сервере
[12:28:23] [Server thread/INFO]: com.mojang.authlib.GameProfile@27add873[id=e95a7924-9c08-315a-9a50-41838be89456,name=lroneaqle,properties={textures=[com.mojang.authlib.properties.Property@41fa89ae]},legacy=false] (/185.57.30.92:15540) lost connection: §cТакой игрок уже играет на сервере

#### Server ####
git-Spigot-21fe707-e1ebe52 ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1043
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.1.0

#### How to reproduce the issue (is it random / always happens / side conditions)?
Maybe this error appears when this player is already on the server and his nickname once again trying to go

#### Have you made any (noteworthy) changes to the default configuration of NCP?
There is, but only on the blocked commands

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
ViaVersion

**Comment by asofold** [comment]
Are you sure your ProtocolLib version is the latest appropriate one for 1.8.8? (Haven't checked yet, but it needs to be checked.)

The temporary player thing is problematic, i'll add in a check for that very spot.

**Comment by asofold** [comment]
Latest build contains/activates a workaround for this issue.

**Comment by Skilzar** [comment]
Thank you

**Comment by asofold** [comment]
Does it work?

**Comment by Skilzar** [comment]
Oh no no. Is the latest build NCP 1046
[18:25:42] [Netty Epoll Server IO #3/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:143) ~[ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$42dbc21b.getWorld(<generated>) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.net.NetConfigCache.getConfig(NetConfigCache.java:41) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.NetConfigCache.getConfig(NetConfigCache.java:28) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.NetDataFactory.getData(NetDataFactory.java:47) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.NetStatic.getWorldConfig(NetStatic.java:184) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.CatchAllAdapter.onPacketReceiving(CatchAllAdapter.java:75) ~[NoCheatPlus.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
[18:25:42] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload@2664e181[
    a=REGISTER
    b=UnpooledHeapByteBuf(ridx: 0, widx: 27, cap: 27)
  ]

**Comment by asofold** [comment]
Yes, there are more spots to cover :).

**Comment by Skilzar** [comment]
The bug is still there. Use NCP version 1048.

**Comment by asofold** [comment]
Please use build 1052 or later, to see if the fix attempt works.

**Comment by Skilzar** [comment]
Updated the plugin to the NCP 1054 but still have this error

[11:12:19] [Netty Epoll Server IO #2/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:143) ~[ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$36e00e4f.getWorld(<generated>) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.chat.ChatConfig.getConfig(ChatConfig.java:74) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.chat.ChatData.getData(ChatData.java:62) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.NetStatic.getWorldConfig(NetStatic.java:186) ~[NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.CatchAllAdapter.onPacketReceiving(CatchAllAdapter.java:75) ~[NoCheatPlus.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [craftbukkit.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[11:12:19] [Server thread/INFO]: [mcjobs] Unable to load Dugie.dat...  Creating file!
[11:12:19] [Netty Epoll Server IO #2/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload@6af13f1d[
    a=REGISTER
    b=UnpooledHeapByteBuf(ridx: 0, widx: 27, cap: 27)
  ]

**Comment by asofold** [comment]
Does this still happen with the appropriate versions of NCP (1084 or later) and ProtocolLib (latest?)
