### ISSUE TITLE
BlockPistonExtendEvent

### ISSUE THREAD

**Issue by Xayanix** [NoCheatPlus/Issues#354]
#### Short description of the issue.
Error log says everything.

#### Complete output of the _ncp version_ command (please prefer text here).
http://scr.hu/0duk/2yes8
#### How to reproduce the issue (is it random / always happens / side conditions)?
I don't know.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
No.

[10:59:13] [Server thread/ERROR]: Could not pass event BlockPistonExtendEvent to NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1044
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Survival.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Survival.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [Survival.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockPiston.e(BlockPiston.java:69) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockPiston.doPhysics(BlockPiston.java:46) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockLever.interact(BlockLever.java:219) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:391) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:666) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [Survival.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Survival.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.NullPointerException
	at fr.neatmonster.nocheatplus.utilities.map.BlockProperties.isSameShape(BlockProperties.java:3876) ~[?:?]
	at fr.neatmonster.nocheatplus.utilities.map.BlockCache$BlockCacheNode.equals(BlockCache.java:179) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.blocks.changetracker.BlockChangeTracker$BlockChangeEntry.isRedundant(BlockChangeTracker.java:265) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.blocks.changetracker.BlockChangeTracker.addBlockChange(BlockChangeTracker.java:484) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.blocks.changetracker.BlockChangeTracker.addPistonBlock(BlockChangeTracker.java:370) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.blocks.changetracker.BlockChangeTracker.addPistonBlocks(BlockChangeTracker.java:345) ~[?:?]
	at fr.neatmonster.nocheatplus.compat.blocks.changetracker.BlockChangeListener.onPistonExtend(BlockChangeListener.java:107) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Survival.jar:git-PaperSpigot-1f7d532]
	... 43 more

**Comment by asofold** [comment]
Will be fixed in the upcoming build 1053. Thanks a lot!
