### ISSUE TITLE
Some spam idk what

### ISSUE THREAD

**Issue by Someone-NEW** [NoCheatPlus/Issues#355]
I dont know what will this mean??? even i dont know to explain this is from the start log file thank you for the looking this. I use Spigot 1.10.2

[02:06:59] [Server thread/INFO]: [NoCheatPlus] Post-enable running...
[02:07:00] [Server thread/INFO]: [NoCheatPlus] Post-enable finished.
[02:07:00] [Craft Scheduler Thread - 21/WARN]: Exception in thread "Craft Scheduler Thread - 21" 
[02:07:00] [Craft Scheduler Thread - 21/WARN]: org.apache.commons.lang.UnhandledException: Plugin ChestShop v3.8.12 generated an exception while executing task 86
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.Acrobot.ChestShop.Metrics.postPlugin(Metrics.java:335)
	at com.Acrobot.ChestShop.Metrics.access$400(Metrics.java:57)
	at com.Acrobot.ChestShop.Metrics$1.run(Metrics.java:223)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Janmm14** [comment]
Issue is the `ChestShop` plugin. Do not ask fir suuport here, but here: (even if you don't run an 1.11 server) https://www.spigotmc.org/wiki/spigot-1-11-plugin-compatibility-list/

**Comment by Someone-NEW** [comment]
ChestShop omg how do you know that? but thank you for ansver

**Comment by asofold** [comment]
Closing as invalid then :).
