### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by RikoDEV** [NoCheatPlus/Issues#392]
I see error in console.

```
[14:06:55 ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/EnumWrappers$EnumConverter
        at com.comphenix.protocol.wrappers.EnumWrappers.getEntityUseActionConverter(EnumWrappers.java:554) ~[ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.events.PacketContainer.getEntityUseActions(PacketContainer.java:799) ~[ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at fr.neatmonster.nocheatplus.checks.net.protocollib.UseEntityAdapter.onPacketReceiving(UseEntityAdapter.java:70) ~[NoCheatPlus.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.11.2.jar:git-Paper-1060]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.1-SNAPSHOT-b347]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.11.2.jar:git-Paper-1060]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.11.2.jar:git-Paper-1060]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[14:06:55 ERROR]: Parameters:
  net.minecraft.server.v1_11_R1.PacketPlayInUseEntity@61507eec[
    a=19310
    action=INTERACT
    c=<null>
    d=OFF_HAND
  ]
```
[15:24:58 INFO]: ---- Version information ----
[15:24:58 INFO]: #### Server ####
[15:24:58 INFO]: git-Paper-1060 ~MC: 1.11.2~
[15:24:58 INFO]:   detected: 1.11.2
[15:24:58 INFO]: #### NoCheatPlus ####
[15:24:58 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1066
[15:24:58 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[15:24:58 INFO]: Features:
[15:24:58 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[15:24:58 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[15:24:58 INFO]:   defaults: pvpKnockBackVelocity
[15:24:58 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[15:24:58 INFO]: Hooks: AllViolations~NCP~ 1.0
[15:24:58 INFO]: #### Related Plugins ####
[15:24:58 INFO]: ProtocolLib v4.2.1-SNAPSHOT-b348

**Comment by asofold** [comment]
This could be fixed with build 1087 (and later) - did not address explicitly but it is built against ProtocolLib-API 4.2.1.

**Comment by asofold** [comment]
Assume fixed.
