### ISSUE TITLE
 Do I need to worry about this error / alert message?

### ISSUE THREAD

**Issue by comonier** [NoCheatPlus/Issues#398]
`[12:53:03] [Server thread/ERROR]: Could not pass event FakeBlockBreakEvent to CompatNoCheatPlus v6.6.0-RC-sASO-bXXX
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:104) [mcMMO.jar:?]
	at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.dropBlocks(WoodcuttingManager.java:120) [mcMMO.jar:?]
	at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.processTreeFeller(WoodcuttingManager.java:104) [mcMMO.jar:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:218) [mcMMO.jar:?]
	at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:850) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/utilities/BlockProperties
	at me.asofold.bpl.cncp.hooks.mcmmo.HookFacadeImpl.getToolProps(HookFacadeImpl.java:137) ~[?:?]
	at me.asofold.bpl.cncp.hooks.mcmmo.HookFacadeImpl.blockBreakLowest(HookFacadeImpl.java:171) ~[?:?]
	at me.asofold.bpl.cncp.hooks.mcmmo.HookmcMMO.onBlockBreakLowest(HookmcMMO.java:142) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor639.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	... 28 more`

**Comment by MarkElf** [comment]
Mind providing a screenshot of the output of /ncp version?

**Comment by asofold** [comment]
@comonier 
Usually you do have to worry, because compatibility may suffer, or in worst case some player can bypass checks for longer than necessary - not sure why this is closed, though.

NCP dev builds (1.11.2 obligatory): https://ci.md-5.net/job/NoCheatPlus/
CNCP build 87 or later needed: https://ci.md-5.net/job/CompatNoCheatPlus/

Possibly you have been using an incompatible pair of NCP+cncp, updated and resolved the issue that way?


@MarkElf @comonier 
Concerning the full output of the 'ncp version' command: Yes please :), despite the cncp version being contained in the log, it still gives the fastest quick-judge thing on version/feature-related questions and issues. Concerning 'screenshot' - i'd prefer textual output for the version command, really :) - you can also get it from the client log file (typically somewhere under .minecraft, not sure if it's in the folder of the used profile, if you set a folder). If you must use a screenshot ensure to upload it to github directly (underneath the blue dashed line is the way to do it: 'Attach files by dragging & dropping, selecting them, or pasting from the clipboard'. In some cases logs or ingame-screenshots may be meant to expire, in that case linking to simple sites or a gist can be ok - really prefer if external sites work without any of javascript and worse :).

Too much text - i need to put this/such somewhere where i can link it ....

**Comment by comonier** [comment]
TY it solve the problem

**Comment by asofold** [comment]
Thank you for confirmation. That's also important to be able to exclude rare issues, sometimes.
