### ISSUE TITLE
Error console post-enable

### ISSUE THREAD

**Issue by Max633** [NoCheatPlus/Issues#407]
Hello

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

```
[15:43:54 INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[15:43:54 INFO]: [NoCheatPlus] Post-enable running...
[15:43:55 INFO]: [NoCheatPlus] Post-enable finished.
[15:43:55 ERROR]: null
java.io.FileNotFoundException: http://updater.azrank.minecraft.rutr.pl/?protocol=1&a=1&b=3&c=b5
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[?:1.8.0_121]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_121]
        at pl.rutr.minecraft.azrank.UpdateChecker.run(UpdateChecker.java:81) [AZRank-1.3.b5.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Thank you sir :)

**Comment by MarkElf** [comment]
I believe the error is from the plugin AZRank, not ncp.

**Comment by asofold** [comment]
Yes :) - postEnable routine had just finished, and the exception was printed, but the exception seems to be from another plugin (auto updated of azrank something).

**Comment by Max633** [comment]
Ok thank you, AZrank is delete... Plugin not up to date.

**Comment by asofold** [comment]
Closing as resolved.
