### ISSUE TITLE
Could not pass event PlayerMoveEvent to NoCheatPlus

### ISSUE THREAD

**Issue by hurrgurl** [NoCheatPlus/Issues#409]
#### Short description of the issue.
Just an error, not sure if anything serious.

```
Could not pass event PlayerMoveEvent to NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1078
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1080]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1080]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1080]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1080]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:617) ~[patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1080]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1080]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1080]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at fr.neatmonster.nocheatplus.utilities.location.LocUtil.set(LocUtil.java:208) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onCancelledMove(MovingListener.java:1448) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMoveMonitor(MovingListener.java:1423) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor159.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1080]
	... 16 more
```

#### Complete output of the _ncp version_ command (please prefer text here).

```
[10:52:15 INFO]: ---- Version information ----
[10:52:15 INFO]: #### Server ####
[10:52:15 INFO]: git-Paper-1080 ~MC: 1.11.2~
[10:52:15 INFO]:   detected: 1.11.2
[10:52:15 INFO]: #### NoCheatPlus ####
[10:52:15 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1078
[10:52:15 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[10:52:15 INFO]: Features:
[10:52:15 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1
| BlocksMC1_11
[10:52:15 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnt
veFrequency
[10:52:15 INFO]:   defaults: pvpKnockBackVelocity
[10:52:15 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingP
[10:52:15 INFO]: Hooks: AllViolations~NCP~ 1.0 | Autobanner 0.1
[10:52:15 INFO]: #### Related Plugins ####
[10:52:15 INFO]: ProtocolLib v4.2.1

```
#### How to reproduce the issue (is it random / always happens / side conditions)?
Not sure. I see it from time to time. It's been around for at least a month.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Nothing noteworthy.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Besides using vanilla speed (up to 4) no.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Sorry, don't know how to reproduce.

**Comment by asofold** [comment]
Thank you - this appears to happen, when other plugins cancel a PlayerMoveEvent, e.g. WorldGuard.

Severiy ~ uncertain, might break other plugin functionality (likely rare/not), 

Fix with builf 1079 or later.
