### ISSUE TITLE
Hello, I am using Build 1082 version there is an error

### ISSUE THREAD

**Issue by qiuDar** [NoCheatPlus/Issues#413]
This is an error message, English is not good, please forgive me.

`[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m [0;33;22m[[0;36;1mYum [0;32;1m事件监控[0;33;22m] [0;33;22m插件 [0;36;1mNoCheatPlus [0;33;22m处理 [0;35;1mPlayerInteractEvent [0;33;22m事件时发生异常![m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m [0;33;22m异常名称: [0;31;1mjava.lang.NullPointerException[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m [0;33;22m异常说明: [0;36;22mnull[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m [0;33;22m简易错误信息如下:[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m     [0;33;1m位于 [0;31;1mfr.neatmonster.nocheatplus.checks.blockinteract.Reach.check([0;31;22mReach.java:63[0;31;1m)[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m     [0;33;1m位于 [0;31;1mfr.neatmonster.nocheatplus.checks.blockinteract.BlockInteractListener.onPlayerInteract([0;31;22mBlockInteractListener.java:161[0;31;1m)[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m     [0;33;1m位于 [0;31;1msun.reflect.GeneratedMethodAccessor85.invoke([0;31;22m未知:-1[0;31;1m)[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m     [0;33;1m位于 [0;31;1msun.reflect.DelegatingMethodAccessorImpl.invoke([0;31;22m未知:-1[0;31;1m)[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m     [0;33;1m位于 [0;31;1mjava.lang.reflect.Method.invoke([0;31;22m未知:-1[0;31;1m)[m
[21:06:02] [Server thread/INFO]: [0;33;22m[[0;36;1mYum[0;33;22m][m [0;31;1m开发人员调试信息如下:[m
[21:06:02] [Server thread/WARN]: java.lang.NullPointerException
[21:06:02] [Server thread/WARN]: 	at fr.neatmonster.nocheatplus.checks.blockinteract.Reach.check(Reach.java:63)
[21:06:02] [Server thread/WARN]: 	at fr.neatmonster.nocheatplus.checks.blockinteract.BlockInteractListener.onPlayerInteract(BlockInteractListener.java:161)
[21:06:02] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
[21:06:02] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:06:02] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[21:06:02] [Server thread/WARN]: 	at pw.yumc.Yum.inject.ListenerInjector.execute(ListenerInjector.java:88)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[21:06:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:717)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[21:06:02] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:06:02] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:06:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:06:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
`

**Comment by MarkElf** [comment]
Please post the output of /ncp version.

**Comment by qiuDar** [comment]
`>ncp version
[21:44:36 INFO]: ---- Version information ----
[21:44:36 INFO]: #### Server ####
[21:44:36 INFO]: git-Spigot-21fe707-e1ebe52 ~MC: 1.8.8~
[21:44:36 INFO]:   detected: 1.8.8
[21:44:36 INFO]: #### NoCheatPlus ####
[21:44:36 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1082
[21:44:36 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[21:44:36 INFO]: Features:
[21:44:36 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[21:44:36 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[21:44:36 INFO]:   defaults: pvpKnockBackVelocity
[21:44:36 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[21:44:36 INFO]: Hooks: AllViolations~NCP~ 1.0
[21:44:36 INFO]: #### Related Plugins ####
[21:44:36 INFO]: ProtocolLib v4.2.1
`

**Comment by asofold** [comment]
(Technically a BlockInteractEvent seems to fire with a null block set, for clicking air or blocks - and for some reason NCP doesn't ignore them anymore / nor handle them differently - need to check why / what.)

We have this: pw.yumc.Yum.inject.ListenerInjector
Is there a plugin named 'Yum' - what does it do?

**Comment by qiuDar** [comment]
Yum is a multifunctional management plug-ins, including performance testing and plug-in loading overloading or unloading. Similar to the PlugMan.

**Comment by asofold** [comment]
Ok. Looks like the change to not ignore null blocks had been introduced with elytra boost support - most certainly this hadn't been intended. I'll fix this somehow, though i am not sure, if i should cancel out the event or just ignore it.

**Comment by qiuDar** [comment]
Thank you.

**Comment by asofold** [comment]
First fix attempt is in build 1083.

**Comment by qiuDar** [comment]
That's great!Has no problem!
