### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by bertek41** [NoCheatPlus/Issues#468]
Hey i get error on my 1.8.8 spigot java 8 server latest nocheatplus (on spigot)

```
[14:29:51] [Server thread/INFO]: [NoCheatPlus] Post-enable running...
[14:29:52] [Server thread/INFO]: [NoCheatPlus] Post-enable finished.
[14:29:53] [Server thread/WARN]: java.net.UnknownHostException: api.bukget.org
[14:29:53] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[14:29:53] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[14:29:53] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[14:29:53] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[14:29:53] [Server thread/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[14:29:53] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[14:29:53] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
[14:29:53] [Server thread/WARN]: 	at ch.dragon252525.frameprotect.util.UpdateChecker.updateInfo(UpdateChecker.java:95)
[14:29:53] [Server thread/WARN]: 	at ch.dragon252525.frameprotect.util.UpdateChecker.lambda$start$0(UpdateChecker.java:45)
[14:29:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:29:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[14:29:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[14:29:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:29:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:29:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:29:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

Edit: I fixed the error. I turned off the FrameProtect update.

**Comment by 0-x-2-2** [comment]
not a nocheatplus issue

**Comment by CaptainObvious0** [comment]
Yes, this is not a NoCheatPlus issue. As you can see it says post-enable finished meaning nocheatplus is done loading any anything after it not related to nocheatplus.

**Comment by Janmm14** [comment]
@bertek41 Please press close issue.

**Comment by asofold** [comment]
~ ch.dragon252525.frameprotect.util.UpdateChecker
