### ISSUE TITLE
Error on disable

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#484]
#### Short description of the issue.
I seem to get an error when shutting down my server. 
#### Complete output of the _ncp version_ command (please prefer text here).
Will update to include later - 1.8 + development build 1113
#### How to reproduce the issue (is it random / always happens / side conditions)?
Seems random
#### Have you made any (noteworthy) changes to the default configuration of NCP?
None
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
None
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
https://hastebin.com/oheqifuzuy.vbs

**Comment by 0-x-2-2** [comment]
the hastebin is empty?

**Comment by Janmm14** [comment]
@w-o-a-h its not empty, maybe their backend servers were down
content of https://hastebin.com/oheqifuzuy.vbs:
```
14.08 22:58:30 [Server] INFO Disabling NoCheatPlus v3.15.2-SNAPSHOT-sMD5NET-b1111
14.08 22:58:30 [Server] ERROR Error occurred while disabling NoCheatPlus v3.15.2-SNAPSHOT-sMD5NET-b1111 (Is it up to date?)
14.08 22:58:30 [Server] INFO java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/config/ConfigManager$3
14.08 22:58:30 [Server] INFO at fr.neatmonster.nocheatplus.config.ConfigManager.setActionFactoryFactory(ConfigManager.java:103) ~[?:?]
14.08 22:58:30 [Server] INFO at fr.neatmonster.nocheatplus.config.ConfigManager.cleanup(ConfigManager.java:142) ~[?:?]
14.08 22:58:30 [Server] INFO at fr.neatmonster.nocheatplus.NoCheatPlus.onDisable(NoCheatPlus.java:796) ~[?:?]
14.08 22:58:30 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
14.08 22:58:30 [Server] INFO Caused by: java.lang.ClassNotFoundException: fr.neatmonster.nocheatplus.config.ConfigManager$3
14.08 22:58:30 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_71]
14.08 22:58:30 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
14.08 22:58:30 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
14.08 22:58:30 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
```

**Comment by Janmm14** [comment]
This error is likely occurring when trying to reload while NoCheatPlus.jar got updated on the disk and not all relevant classes to unload NoCheatPlus were loaded.
