### ISSUE TITLE
NoCheatPlus Console Error - Latest Dev Build

### ISSUE THREAD

**Issue by TheDGOfficial** [NoCheatPlus/Issues#498]
#### Short description of the issue.

NoCheatPlus throws a error to console with latest dev build and protocollib 3.7.0.

#### Complete output of the _ncp version_ command (please prefer text here).

3.15.2-SNAPSHOT-sMD5NET-b1113

#### How to reproduce the issue (is it random / always happens / side conditions)?

is it random

#### Have you made any (noteworthy) changes to the default configuration of NCP?

Yes but i think does not cause of this error

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

No

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

```
[18:17:00] [Netty IO #1/ERROR]: [NoCheatPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for NoCheatPlus
java.lang.NullPointerException
	at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:169) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:158) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:201) ~[ProtocolLib.jar:?]
	at fr.neatmonster.nocheatplus.checks.net.protocollib.UseEntityAdapter.onPacketReceiving(UseEntityAdapter.java:160) ~[NoCheatPlus.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:635) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:602) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:300) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:266) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:524) [ProtocolLib.jar:?]
	at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:261) [ProtocolLib.jar:?]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[18:17:00] [Netty IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_7_R4.PacketPlayInUseEntity@30ddca06[
    a=1445
    action=<null>
    timestamp=1509898620470
  ]
```

**Comment by asofold** [comment]
Will be 'fixed' in build 1148.

In fact i am not sure how/why this happens, there should be another part of the code running, but multi client protocol support plugins and custom Spigot builds might alter things here.

The 'fix' will prevent the exception log. Otherwise the packet can't be interpreted, so there is no difference to before, in terms of functionality.
